package:
  name: pylidar
  version: "0.0.2"

source:
  path: ..

build:
  noarch: python
  number: 0
  script: python setup.py install

requirements:
  host:
    - python
    - setuptools
  run:
    - python

about:
  home: "https://github.com/kazumichiINOUE/pyLIDAR"
  license: "MIT"

